server:
  port: 8080

spring:
  cloud:
    config:
      uri: http://config-server:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://user-service:8084
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**
        - id: logging-service
          uri: lb://LOGGING-SERVICE
          predicates:
            - Path=/api/v1/logs/**

  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

logging:
  level:
    org.springframework: INFO
    com.example.userservice: DEBUG
