logging:
  level:
    org.springframework.cloud: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth-servicedb
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 