spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://config-server:8888

server:
  port: 8082

logging:
  level:
    org.springframework: INFO
    com.example.userservice: DEBUG 