# Server Port
server:
  port: 8082

# Application Name
spring:
  application:
    name: auth-service

  # Cloud Config Server
  cloud:
    config:
      uri: http://config-server:8888

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/auth-servicedb
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # LDAP Configuration (Optional, Keep if Needed)
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389

# JWT Configuration
jwt:
  secret: 90e041074e7a755edefc860d1947e8dd345d8c07bea083ea5d9a6dc51fe02561
  expiration: 3600
