spring:
  application:
    name: logging-service
  cloud:
    config:
      uri: http://config-server:8888

server:
  port: 8083

logging:
  level:
    org.springframework: INFO
    com.example.userservice: DEBUG 